#!/bin/bash -e

. /usr/lib/scylla/scylla_lib.sh

if [ ! -f /etc/scylla/ami_configured ]; then
    /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --setup-nic --ami
    /usr/lib/scylla/scylla-ami/ds2_configure.py
    /usr/lib/scylla/scylla-ami/scylla_create_devices
    if [ `ec2_is_supported_instance_type` -eq 1 ]; then
        /usr/lib/scylla/scylla_io_setup --ami
    fi
    if [ "`mount|grep /var/lib/scylla`" != "" ]; then
        /usr/lib/scylla/scylla_coredump_setup --dump-to-raiddir
    else
        /usr/lib/scylla/scylla_coredump_setup
    fi
    touch /etc/scylla/ami_configured
else
    /usr/lib/scylla/scylla-ami/scylla_create_devices
fi
