#!/bin/sh -e
#
#  Copyright (C) 2015 ScyllaDB

if [ "`id -u`" -ne 0 ]; then
    echo "Requires root permission."
    exit 1
fi

print_usage() {
    echo "build_install_ami --localrpm --unstable"
    echo "  --localrpm  deploy locally built rpms"
    echo "  --unstable  use unstable branch"
    exit 1
}
for OPT in "$@"; do
    case "$OPT" in
        "--localrpm")
            INSTALL_ARGS="$INSTALL_ARGS --local-pkg /home/centos"
            shift 1
            ;;
        "--unstable")
            INSTALL_ARGS="$INSTALL_ARGS --unstable"
            shift 1
            ;;
        "-h" | "--help")
            print_usage
            ;;
    esac
done

yum remove -y abrt
chmod a+rx /home/centos/scylla_install_pkg
sh -x -e /home/centos/scylla_install_pkg $INSTALL_ARGS
grep -v ' - mounts' /etc/cloud/cloud.cfg > /tmp/cloud.cfg
mv /tmp/cloud.cfg /etc/cloud/cloud.cfg
mv /home/centos/scylla-ami/scylla-ami-setup.service /usr/lib/systemd/system/
mv /home/centos/scylla-ami /usr/lib/scylla/scylla-ami
systemctl daemon-reload
systemctl enable scylla-ami-setup.service
sh -x -e /usr/lib/scylla/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup
