#!/bin/bash -e

is_supported_instance_type() {
    TYPE=`curl http://169.254.169.254/latest/meta-data/instance-type|cut -d . -f 1`
    case $TYPE in
        "m3"|"c3"|"i2") echo 1;;
        *) echo 0;;
    esac
}

RAIDCNT=`grep xvdb /proc/mdstat | wc -l`
RAIDDEV=`grep xvdb /proc/mdstat | awk '{print $1}'`

if [ $RAIDCNT -ge 1 ]; then
    echo "RAID already constructed."
    if [ "`mount|grep /var/lib/scylla`" = "" ]; then
        mount -o noatime /dev/$RAIDDEV /var/lib/scylla
    fi
else
    echo "RAID does not constructed, going to initialize..."
    DISKS=""
    for i in /dev/xvd{b..z}; do
        if [ -b $i ];then
            echo "Found disk $i"
            if [ "$DISKS" = "" ]; then
                DISKS=$i
            else
                DISKS="$DISKS,$i"
            fi
        fi
    done

    if [ "$DISKS" != "" ]; then
        /usr/lib/scylla/scylla_raid_setup --disks $DISKS
    fi
fi

if [ ! -f /etc/scylla/ami_configured ]; then
    NR_CPU=`cat /proc/cpuinfo |grep processor|wc -l`
    if [ $NR_CPU -lt 8 ]; then
        /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --ami
    else
        NR=$((NR_CPU - 1))
        /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --setup-nic --ami
        /usr/lib/scylla/scylla_cpuset_setup --cpuset 1-$NR --smp $NR
    fi
    /usr/lib/scylla/scylla-ami/ds2_configure.py
    if [ `is_supported_instance_type` -eq 1 ]; then
        /usr/lib/scylla/scylla_io_setup --ami
    fi
    if [ "`mount|grep /var/lib/scylla`" != "" ]; then
        /usr/lib/scylla/scylla_coredump_setup --dump-to-raiddir
    else
        /usr/lib/scylla/scylla_coredump_setup
    fi
    touch /etc/scylla/ami_configured
fi
