#!/bin/sh -e
#
#  Copyright (C) 2015 ScyllaDB

if [ "`id -u`" -ne 0 ]; then
    echo "Requires root permission."
    exit 1
fi

print_usage() {
    echo "build_install_ami --localrpm --unstable"
    echo "  --localrpm  deploy locally built rpms"
    echo "  --unstable  use unstable branch"
    exit 1
}
. /etc/os-release
for OPT in "$@"; do
    case "$OPT" in
        "--localrpm")
            INSTALL_ARGS="$INSTALL_ARGS --local-pkg /home/$ID"
            shift 1
            ;;
        "--unstable")
            INSTALL_ARGS="$INSTALL_ARGS --unstable"
            shift 1
            ;;
        "-h" | "--help")
            print_usage
            ;;
    esac
done

if [ "$ID" = "ubuntu" ]; then
    apt-get purge -y apport
else
    yum remove -y abrt
    mv /home/centos/scylla-ami/scylla-ami-setup.service /usr/lib/systemd/system/
    systemctl daemon-reload
    systemctl enable scylla-ami-setup.service
fi
chmod a+rx /home/$ID/scylla_install_pkg
sh -x -e /home/$ID/scylla_install_pkg $INSTALL_ARGS
grep -v ' - mounts' /etc/cloud/cloud.cfg > /tmp/cloud.cfg
mv /tmp/cloud.cfg /etc/cloud/cloud.cfg
mv /home/$ID/scylla-ami /usr/lib/scylla/scylla-ami
sh -x -e /usr/lib/scylla/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup
sh -x -e /usr/lib/scylla/scylla_sysconfig_setup --ami
sh -x -e /usr/lib/scylla/scylla_bootparam_setup --ami
