#!/bin/sh -e

RAIDCNT=`grep xvdb /proc/mdstat | wc -l`
RAIDDEV=`grep xvdb /proc/mdstat | awk '{print $1}'`

if [ $RAIDCNT -ge 1 ]; then
    echo "RAID already constructed."
    if [ "`mount|grep /var/lib/scylla`" = "" ]; then
        mount -o noatime /dev/$RAIDDEV /var/lib/scylla
    fi
else
    echo "RAID does not constructed, going to initialize..."
    DISKS=""
    for i in /dev/xvd{b..z}; do
        if [ -b $i ];then
            echo "Found disk $i"
            if [ "$DISKS" = "" ]; then
                DISKS=$i
            else
                DISKS="$DISKS,$i"
            fi
        fi
    done

    if [ "$DISKS" != "" ]; then
        /usr/lib/scylla/scylla_raid_setup --disks $DISKS
    fi
fi

if [ ! -f /etc/scylla/ami_configured ]; then
    /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --setup-nic --ami
    /usr/lib/scylla/scylla-ami/ds2_configure.py
    touch /etc/scylla/ami_configured
fi
